HOST: http://api.naics.us/v0/

--- NAICS API ---

---
The [North American Industry Classification System](http://www.census.gov/eos/www/naics/) (NAICS) is used by the U.S. Federal Government to organize 
different types of businesses economic analysis purposes, and while there are different types of numbering systems out there that do this, a lot of 
local municipalities have also started adopting it for their own business classification purposes. The NAICS codes and descriptions are revised every
five years (latest: 2012; next: 2017), and while information is freely provided as PDFs or Excel spreadsheets and hosted by the U.S. Census Bureau, 
no machine-readable API exists for retrieving this data that can be easily used in applications. Until now.
---

--
Retrieving NAICS codes
How to get codes, and information related to that code

#### Data Schema
* __code__ This is the 2-6 digit NAICS code.
* __title__ This is the name of the NAICS code.
* __seq_no__ This is a sequence number provided by NAICS and appears to be used as a primary key in databases by some agencies. Do not use this except for backwards-compatibility with other software.
* __change_indicator (2012 NAICS only)__ If present, indicates whether this code changed from the previous (2007) NAICS.
    * __1 = title changed__ from 2007 NAICS, but no content has changed.
    * __2 = new code__ in 2012 NAICS.
    * __3 = content changed__ from 2007 NAICS, and title may or may not have changed.
* __trilateral (2012 NAICS only)__ If present, indicates that there is a trilateral agreement between Canada, Mexico, and the United States to use a comparable definition of this industry for this code.
* __description__ If present, this is the text description of this NAICS Code provided by the NAICS Definition File.
* __description_code__ If present, this refers to another NAICS Code description. This will never be present if __description__ for this code is present.
* __examples__ If present, this is an array of illustrative examples provided by the NAICS Definition File.
* __xrefs__ If present, this is an array of cross-references to other NAICS codes that should be used to fine-tune a business classification, provided by the NAICS Definition File. Both the text description of a cross-reference and its reference NAICS code is provided.
* __index__ (6-digit codes only) If present, this is an array of other titles that belong under this NAICS code, provided by the NAICS Index File. Very useful as a keyword search to determine where specific businesses should be classified. 

--

Get all NAICS codes for a given year (only 2007 and 2012 are available right now.)
GET /q{?year}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "name": "2012 NAICS Codes",
    "year": 2012,
    "items": [
        {
            "seq_no": 1,
            "code": 11,
            "title": "Agriculture, Forestry, Fishing and Hunting",
            "trilateral": 1
        },
        {  ...  }
    ]
}

Get a single NAICS code.
GET /q{?year,code}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "seq_no": 1663,
    "code": 541430,
    "title": "Graphic Design Services",
    "index": [
        "Art services, commercial",
        "Art services, graphic",
        "Art studios, commercial",
        "Artists, independent commercial",
        "Artists, independent graphic",
        "Artists, independent medical",
        "Commercial art services",
        "Commercial artists, independent",
        "Commercial illustration services",
        "Commercial illustrators, independent",
        "Communication design services, visual",
        "Corporate identification (i.e., logo) design services",
        "Graphic art and related design services",
        "Graphic artists, independent",
        "Graphic design services",
        "Illustrators, independent commercial",
        "Medical art services",
        "Medical artists, independent",
        "Medical illustration services",
        "Medical illustrators, independent",
        "Silk screen design services",
        "Studios, commercial art"
    ]
}

Get all NAICS codes above in the hierarchy of the requested code.
GET /q{?year,code,above}
> Accept: application/json
< 200
< Content-Type: application/json
[
    {
        "seq_no": 1402,
        "code": 51,
        "title": "Information",
        "trilateral": 1
    },
    {
        "seq_no": 1470,
        "code": 519,
        "title": "Other Information Services",
        "trilateral": 1
    },
    {
        "seq_no": 1471,
        "code": 5191,
        "title": "Other Information Services",
        "trilateral": 1
    },
    {
        "seq_no": 1474,
        "code": 51912,
        "title": "Libraries and Archives",
        "trilateral": 1
    }
]

Get all NAICS codes below in the hierarchy of the requested code.
GET /q{?year,code,below}
> Accept: application/json
< 200
< Content-Type: application/json
[
    {
        "seq_no": 1403,
        "code": 511,
        "title": "Publishing Industries (except Internet)",
        "trilateral": 1
    },
    {
        "seq_no": 1404,
        "code": 5111,
        "title": "Newspaper, Periodical, Book, and Directory Publishers",
        "trilateral": 1
    },
    {
        "seq_no": 1405,
        "code": 51111,
        "title": "Newspaper Publishers",
        "trilateral": 1
    },
    {
        "seq_no": 1406,
        "code": 511110,
        "title": "Newspaper Publishers",
    },
    {
        "seq_no": 1407,
        "code": 51112,
        "title": "Periodical Publishers",
        "trilateral": 1
    },
    {
        "seq_no": 1408,
        "code": 511120,
        "title": "Periodical Publishers",
    },
    {  ...  }
]


--
Searching for a NAICS code
Find the NAICS code for the business type
--

Returns an array of all the NAICS codes that contain search terms in the title or index listing. 

Currently, this does not search description, illustrative examples, or cross references because we don't have this information yet.

Example shows search term for "libraries"
GET /s{?year,terms}
> Accept: application/json
< 200
< Content-Type: application/json
[
    {
        "seq_no": 1474,
        "code": 51912,
        "title": "Libraries and Archives",
        "trilateral": 1
    },
    {
        "seq_no": 1475,
        "code": 519120,
        "title": "Libraries and Archives",
        "index": [
            "Archives",
            "Bookmobiles",
            "Centers for documentation (i.e., archives)",
            "Circulating libraries",
            "Film archives",
            "Lending libraries",
            "Libraries (except motion picture stock footage, motion picture commercial distribution)",
            "Motion picture film libraries, archives",
            "Music archives",
            "Reference libraries"
        ]
    },
    {
        "seq_no": 1424,
        "code": 512120,
        "title": "Motion Picture and Video Distribution",
        "index": [
            "Animated cartoon distribution",
            "Film distribution agencies",
            "Film distribution, motion picture and video",
            "Film libraries, commercial distribution",
            "Motion picture distribution exclusive of production",
            "Motion picture film distributors",
            "Motion picture film libraries",
            "Tape distribution for television",
            "Television show syndicators"
        ]
    },
    {
        "seq_no": 1430,
        "code": 512199,
        "title": "Other Motion Picture and Video Industries",
        "index": [
            "Booking agencies, motion picture",
            "Booking agencies, motion picture or video productions",
            "Film libraries, motion picture or video, stock footage",
            "Film processing laboratories, motion picture",
            "Film restoration services",
            "Laboratory services, motion picture",
            "Libraries, motion picture stock footage film",
            "Libraries, videotape, stock footage",
            "Motion picture booking agencies",
            "Motion picture film laboratories",
            "Motion picture film libraries, stock footage",
            "Motion picture film reproduction for theatrical distribution",
            "Motion picture laboratories",
            "Reproduction of motion picture films for theatrical distribution",
            "Stock footage film libraries",
            "Videotape libraries, stock footage"
        ]
    }
]


--
Conversions between NAICS years and other code systems
For instance, SIP or NIGP.  (this is a placeholder for a potential future feature.)
--
